New option: "slideChange" for slide change callbacks
EnzoMartin/Simple-Rotating-Banner pull request #1
Opened 2017-01-18 23:00 UTC by archinal

In this PR I've added an options parameter 'slideChange' to allow users to provide a slide change callback function. This addition has been helpful for me in site I'm developing where we need to trigger custom behaviour elsewhere on the page as the slides are changed.

I've also updated the README and included a new version of the minified JS, which was done using the latest version of [uglify](https://www.npmjs.com/package/uglify), and is actually more compressed than the old minified javascript.

2017-01-19 08:32 UTC, EnzoMartin requested changes
Appreciate the PR, just a couple small tweaks!

2017-01-19 08:32 UTC, EnzoMartin commented on jquery.simplebanner.js
> +            slideChange: null
I'd prefer to have it called `onChange` to signify it's a function

2017-01-19 08:32 UTC, EnzoMartin commented on jquery.simplebanner.js
> +        if(self.options.slideChange !== null){
Should rather check if it's a function, in case it's erroneously set to an object/boolean/etc.

2017-01-19 08:34 UTC, EnzoMartin commented
Also if you can bump the `minor` version in `bower.json`/`package.json`, and optionally add yourself to contributors in the package.json 👍

2017-01-20 00:42 UTC, archinal commented
Thanks for the feedback! I've made the changes you suggested. Please let me know if there are any other changes you'd like me to make.

2017-01-20 00:58 UTC, EnzoMartin approved these changes

2017-01-20 00:58 UTC, merged

2017-01-20 01:02 UTC, EnzoMartin commented
👍 Awesome!

I've published the new version on NPM, thanks for making the PR!